### ISSUE TITLE
dash-evo-tool-aarch64-mac  panicked!

### ISSUE THREAD

**Issue by sibTamias** [dashpay/dash-evo-tool#21]
Hello!  MacBook Pro M2 chip. I am trying to run version 0.1.1, but I am getting an error:
```
~$ /Users/mn/Downloads/DashEvoTool-aarch64-mac/dash-evo-tool-aarch64-mac
thread 'main' panicked at src/app.rs:108:56:
expected Dash config for mainnet
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x1019600b0 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::habbf9c4f641febb1
   1:        0x10197ffd8 - core::fmt::write::ha36a8060c13608ea
   2:        0x10195c4d8 - std::io::Write::write_fmt::h431832c8ebcc85c9
   3:        0x1019614d8 - std::panicking::default_hook::{{closure}}::h4aa1f60327dfff6a
   4:        0x101961088 - std::panicking::default_hook::h4ebc6eb4ae179807
   5:        0x100e2b478 - dash_evo_tool::logging::initialize_logger::{{closure}}::h784a40d2af6aa85e
   6:        0x101962068 - std::panicking::rust_panic_with_hook::h6a84efe4dcab239c
   7:        0x101961958 - std::panicking::begin_panic_handler::{{closure}}::h5eef292190467fef
   8:        0x101960574 - std::sys::backtrace::__rust_end_short_backtrace::hd7e7925203f20af9
   9:        0x101961648 - _rust_begin_unwind
  10:        0x1019d5fec - core::panicking::panic_nounwind_fmt::hb2df5b6c3d6ab15b
  11:        0x1019d6064 - core::panicking::panic_nounwind::h6b53a509f430e184
  12:        0x1019d6150 - core::panicking::panic_cannot_unwind::hce6968fadcdebaaa
  13:        0x101116d5c - winit::platform_impl::macos::app_state::ApplicationDelegate::app_did_finish_launching::h0ec33804551904d1
  14:        0x191c6ef80 - <unknown>
  15:        0x191d00274 - <unknown>
  16:        0x191d001bc - <unknown>
  17:        0x191c3d634 - <unknown>
  18:        0x192de5c34 - <unknown>
  19:        0x1957c567c - <unknown>
  20:        0x1957c542c - <unknown>
  21:        0x1957c388c - <unknown>
  22:        0x1957c3494 - <unknown>
  23:        0x192e0e8ac - <unknown>
  24:        0x192e0e6a4 - <unknown>
thread caused non-unwinding panic. aborting.
Abort trap: 6
```

Where can I find the value for the `MAIN_NET_WALLET_PRIVATE_KEY=`  in the .env file? Should I leave it empty or enter a value?

New version (0.1.3) without zip extension!  Should it be launched by the terminal? Where is .env ?

**Comment by qwizzie** [comment]
Download latest version v0.1.3 (next version will most likely be packed with zip extension) 
You need to add the .env file with content from  https://github.com/dashpay/dash-evo-tool/blob/master/.env.example in the same folder as the Dash Evo Tool binaries. 
Leave it empty (MAIN_NET_WALLET_PRIVATE_KEY=)
First have dashd fully synced with dash.conf from here : https://github.com/dashpay/dash-evo-tool/blob/master/dash_core_configs/mainnet.conf

**Comment by sibTamias** [comment]
Thanks! I started it only after I changed the permission of the file to executeble:
 ```chmod +x dash-evo-tool-aarch64-mac```

**Comment by gades** [comment]
it's happening when you're openening from different directory 

you should change directory and than run.  I think this is a bug

**Comment by pauldelucia** [comment]
Resolved @ogabrielides ?

**Comment by ogabrielides** [comment]
@pauldelucia Yes. Closing
